packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@livekit/local-inference": false
  "@stripe/stripe-terminal-react-native": true
  browser-tabs-lock: false
  bufferutil: false
  core-js: false
  esbuild: true
  protobufjs: false
  sharp: true
  utf-8-validate: false
minimumReleaseAgeExclude:
  - "@playwright/test@1.62.1"
  - playwright-core@1.62.1
  - playwright@1.62.1
  - jose@6.2.5
  - stripe@22.4.0
  - lucide-react@1.28.0
  - expo-updates@57.0.11 || 57.0.12
  - "@expo/cli@57.0.11 || 57.0.12"
  - "@expo/inline-modules@0.1.4"
  - "@expo/local-build-cache-provider@57.0.5"
  - "@expo/log-box@57.0.2"
  - "@expo/prebuild-config@57.0.10"
  - babel-preset-expo@57.0.5
  - expo-asset@57.0.8
  - expo-constants@57.0.8 || 57.0.9
  - expo-modules-core@57.0.8 || 57.0.9
  - expo@57.0.9 || 57.0.10
  - "@mendable/firecrawl-js@4.32.0"
  - "@aws-sdk/checksums@3.1000.25"
  - "@aws-sdk/client-s3@3.1102.0"
  - "@aws-sdk/core@3.977.5"
  - "@aws-sdk/credential-provider-env@3.972.66"
  - "@aws-sdk/credential-provider-http@3.972.68"
  - "@aws-sdk/credential-provider-ini@3.973.11"
  - "@aws-sdk/credential-provider-login@3.972.73"
  - "@aws-sdk/credential-provider-node@3.972.77"
  - "@aws-sdk/credential-provider-process@3.972.66"
  - "@aws-sdk/credential-provider-sso@3.973.10"
  - "@aws-sdk/credential-provider-web-identity@3.972.72"
  - "@aws-sdk/middleware-sdk-s3@3.972.71"
  - "@aws-sdk/nested-clients@3.997.40"
  - "@aws-sdk/s3-request-presigner@3.1102.0"
  - "@aws-sdk/token-providers@3.1102.0"
  - "@expo/router-server@57.0.5"
  - "@expo/ui@57.0.9"
  - expo-auth-session@57.0.6
  - expo-linking@57.0.5
  - expo-widgets@57.0.8
  - mapbox-gl@3.28.0
