import type {
  AuditEvent,
  BookingSummary,
  EventSummary,
  MatchSummary,
  Metric,
  OrganizationSummary,
  PersonSummary,
  VenueSummary,
  WalletEntry,
} from "./types";

export const demoPlayer: PersonSummary = {
  id: "10000000-0000-4000-8000-000000000010",
  displayName: "Mara Lewis",
  handle: "maralewis",
  initials: "ML",
  homeMarket: "South Bay, Los Angeles",
  roles: ["player"],
  rating: {
    display: 4.62,
    mu: 2148,
    phi: 52,
    sigma: 0.057,
    confidence: "Locked",
    discipline: "beach-2s",
    delta: 0.08,
    percentile: 91,
  },
};

export const demoPeople: readonly PersonSummary[] = [
  demoPlayer,
  {
    id: "10000000-0000-4000-8000-000000000011",
    displayName: "Theo Park",
    handle: "theopark",
    initials: "TP",
    homeMarket: "South Bay, Los Angeles",
    roles: ["player", "coach"],
    rating: {
      display: 4.44,
      mu: 2076,
      phi: 68,
      sigma: 0.061,
      confidence: "Reliable",
      discipline: "beach-2s",
      delta: 0.03,
      percentile: 86,
    },
  },
  {
    id: "10000000-0000-4000-8000-000000000012",
    displayName: "Noa Williams",
    handle: "noawilliams",
    initials: "NW",
    homeMarket: "San Diego",
    roles: ["player"],
    rating: {
      display: 4.78,
      mu: 2212,
      phi: 61,
      sigma: 0.058,
      confidence: "Reliable",
      discipline: "beach-2s",
      delta: -0.02,
      percentile: 94,
    },
  },
  {
    id: "10000000-0000-4000-8000-000000000013",
    displayName: "Sam Rivera",
    handle: "samrivera",
    initials: "SR",
    homeMarket: "South Bay, Los Angeles",
    roles: ["player", "coach", "manager"],
    rating: {
      display: 5.12,
      mu: 2348,
      phi: 44,
      sigma: 0.054,
      confidence: "Locked",
      discipline: "beach-2s",
      delta: 0.01,
      percentile: 97,
    },
  },
  {
    id: "10000000-0000-4000-8000-000000000014",
    displayName: "Elena Torres",
    handle: "elenatorres",
    initials: "ET",
    homeMarket: "South Bay, Los Angeles",
    roles: ["player"],
    rating: {
      display: 4.3,
      mu: 2020,
      phi: 84,
      sigma: 0.063,
      confidence: "Reliable",
      discipline: "beach-2s",
      delta: 0.06,
      percentile: 82,
    },
  },
];

export const demoOrganization: OrganizationSummary = {
  id: "10000000-0000-4000-8000-000000000001",
  slug: "south-bay-volleyball",
  name: "South Bay Volleyball Club",
  legalName: "Beach Elite LLC",
  plan: "club",
  memberCount: 918,
  staffCount: 14,
  venueCount: 3,
  timezone: "America/Los_Angeles",
  stripeStatus: "connected",
};

export const demoVenues: readonly VenueSummary[] = [
  {
    id: "10000000-0000-4000-8000-000000000002",
    organizationId: demoOrganization.id,
    name: "Manhattan Beach Pier",
    city: "Manhattan Beach",
    region: "CA",
    timezone: "America/Los_Angeles",
    courtCount: 12,
    openNow: true,
    latitude: 33.8847,
    longitude: -118.4109,
    tags: ["Oceanfront", "12 courts", "Open play"],
  },
  {
    id: "10000000-0000-4000-8000-000000000005",
    organizationId: demoOrganization.id,
    name: "Hermosa Beach — Pier Courts",
    city: "Hermosa Beach",
    region: "CA",
    timezone: "America/Los_Angeles",
    courtCount: 8,
    openNow: true,
    latitude: 33.8622,
    longitude: -118.4009,
    tags: ["Oceanfront", "Night league", "Pickup"],
  },
  {
    id: "10000000-0000-4000-8000-000000000006",
    organizationId: demoOrganization.id,
    name: "Duna House",
    city: "El Segundo",
    region: "CA",
    timezone: "America/Los_Angeles",
    courtCount: 6,
    openNow: false,
    latitude: 33.9192,
    longitude: -118.4165,
    tags: ["Indoor sand", "Showers", "Late night"],
  },
];

export const demoEvents: readonly EventSummary[] = [
  {
    id: "event-live-open",
    slug: "sunset-open-qualifier",
    title: "Sunset Open — Qualifier",
    kind: "tournament",
    organizationName: demoOrganization.name,
    venueName: "Manhattan Beach Pier",
    shortSummary:
      "A one-night doubles qualifier under the South Bay sunset, with live pools and a true double-elimination finish.",
    description:
      "Check in on the pier, warm up with your division, then move through live pool play into a true double-elimination bracket. Scores, seeds, court calls, and the field update in Duna throughout the night.",
    startsAt: "2026-07-30T23:30:00.000Z",
    endsAt: "2026-07-31T03:30:00.000Z",
    timezone: "America/Los_Angeles",
    price: { amountMinor: 9600, currency: "USD" },
    spotsRemaining: 2,
    capacity: 32,
    ratingRange: [4.2, 5.4],
    location: {
      mode: "venue",
      venueName: "Manhattan Beach Pier",
      address: "100 Manhattan Beach Blvd, Manhattan Beach, CA 90266",
      courtNames: ["Stadium", "Court 1", "Court 2", "Court 3"],
    },
    divisions: [
      {
        id: "20000000-0000-4000-8000-000000000001",
        name: "Open",
        description:
          "The strongest available field with no rating ceiling and a seeded championship bracket.",
        discipline: "beach-2s",
        ratingBasis: "sand-rating-best-8",
        price: { amountMinor: 9600, currency: "USD" },
        spotsRemaining: 2,
        capacity: 32,
        minimumTeams: 8,
        maximumTeams: 16,
        teamFormat: "doubles",
        teamSize: 2,
        surface: "sand",
        gender: "open",
        priceBasis: "per-team",
        ratingMinimum: 4.2,
        tournamentFormat: "double-elimination-true",
        poolPlay: {
          enabled: true,
          teamsPerPool: 4,
          format: "full",
          teamsAdvancing: 2,
        },
        seeding: "sand-rating-best-8",
      },
      {
        id: "20000000-0000-4000-8000-000000000002",
        name: "AA",
        description:
          "Fast, competitive doubles for established teams below the Open rating band.",
        discipline: "beach-2s",
        ratingBasis: "sand-rating-score",
        price: { amountMinor: 7600, currency: "USD" },
        spotsRemaining: 6,
        capacity: 24,
        minimumTeams: 6,
        maximumTeams: 12,
        teamFormat: "doubles",
        teamSize: 2,
        surface: "sand",
        gender: "coed",
        priceBasis: "per-team",
        ratingMinimum: 3.4,
        ratingMaximum: 4.49,
        tournamentFormat: "double-elimination-crossover",
        poolPlay: {
          enabled: true,
          teamsPerPool: 4,
          format: "olympic-crossover",
          teamsAdvancing: 2,
        },
        seeding: "sand-rating-score",
      },
    ],
    tickets: [
      {
        id: "20000000-0000-4000-8000-000000000010",
        name: "Courtside",
        description: "General access to the feature courts and event village.",
        price: { amountMinor: 1200, currency: "USD" },
        quantity: 250,
        remaining: 184,
        waitlistEnabled: false,
        approvalRequired: false,
        availableOnline: true,
        availableInPerson: true,
      },
      {
        id: "20000000-0000-4000-8000-000000000011",
        name: "Sunset Club",
        description:
          "Reserved deck access, hosted drinks, and the championship court.",
        price: { amountMinor: 6500, currency: "USD" },
        quantity: 36,
        remaining: 9,
        waitlistEnabled: true,
        approvalRequired: true,
        availableOnline: true,
        availableInPerson: false,
      },
    ],
    features: [
      {
        id: "feature-sam",
        kind: "guest",
        title: "Guest hosted by Sam Rivera",
        description:
          "Pro player and South Bay coach Sam Rivera opens the finals session.",
        personId: "10000000-0000-4000-8000-000000000013",
        personHandle: "samrivera",
        personInitials: "SR",
      },
      {
        id: "feature-yoga",
        kind: "activity",
        title: "Sunset mobility session",
        description: "A guided warm-up on the sand before first serve.",
      },
      {
        id: "feature-partner",
        kind: "sponsor",
        title: "Hydration village",
        description: "Recovery, shade, and water next to Stadium Court.",
      },
    ],
    policies: [
      {
        id: "policy-weather",
        kind: "policy",
        title: "Weather and event policy",
        markdown:
          "Play may pause for unsafe wind, lightning, or air quality. If the event cannot resume, Duna will show the host's credit or refund decision in your order.",
        required: true,
        requireFullScroll: false,
      },
      {
        id: "waiver-participation",
        kind: "waiver",
        title: "Participation waiver",
        markdown:
          "Beach volleyball includes strenuous activity, uneven surfaces, and contact with equipment and other players. By registering, each player confirms they understand these risks and will follow event safety directions.",
        required: true,
        requireFullScroll: true,
      },
    ],
    live: true,
    tags: ["Open", "Doubles", "$1,500 purse"],
  },
  {
    id: "event-summer-series",
    slug: "south-bay-summer-series-week-5",
    title: "South Bay Summer Series",
    kind: "league",
    organizationName: demoOrganization.name,
    venueName: "Hermosa Beach — Pier Courts",
    shortSummary:
      "Eight Monday nights of balanced co-ed 4s, persistent teams, standings, and live scoring.",
    description:
      "Join as a full team or let Duna balance the field using Sand Rating. Each Monday includes pool play, a featured match, and standings that carry through the full season.",
    startsAt: "2026-08-04T01:00:00.000Z",
    endsAt: "2026-08-04T04:00:00.000Z",
    timezone: "America/Los_Angeles",
    price: { amountMinor: 48000, currency: "USD" },
    spotsRemaining: 4,
    capacity: 24,
    ratingRange: [3.6, 4.8],
    location: {
      mode: "venue",
      venueName: "Hermosa Beach — Pier Courts",
      address: "1 Pier Ave, Hermosa Beach, CA 90254",
      courtNames: ["Courts 1–6"],
    },
    divisions: [
      {
        id: "20000000-0000-4000-8000-000000000020",
        name: "Premier 4s",
        description:
          "Eight-week co-ed season with stable teams, weekly standings, and approved substitutes.",
        discipline: "beach-4s",
        ratingBasis: "sand-rating-ttm",
        price: { amountMinor: 48000, currency: "USD" },
        spotsRemaining: 4,
        capacity: 24,
        minimumTeams: 4,
        maximumTeams: 6,
        teamFormat: "four-person",
        teamSize: 4,
        surface: "sand",
        gender: "coed",
        priceBasis: "per-person",
        ratingMinimum: 3.6,
        ratingMaximum: 4.8,
        tournamentFormat: "single-elimination",
        poolPlay: {
          enabled: true,
          teamsPerPool: 3,
          format: "full",
          teamsAdvancing: 2,
        },
        seeding: "sand-rating-ttm",
      },
    ],
    recurrence: {
      interval: "weekly",
      days: [{ day: "monday", startsAt: "18:00", endsAt: "21:00" }],
      substitutesAllowed: true,
      substituteApprovalRequired: true,
      teamAssignment: "rating-balanced",
    },
    policies: [
      {
        id: "league-rules",
        kind: "policy",
        title: "League rules",
        markdown:
          "Teams play every scheduled week. Substitute requests must be submitted before noon on match day and remain subject to organizer approval.",
        required: true,
        requireFullScroll: false,
      },
    ],
    tags: ["8 weeks", "Co-ed 4s", "Monday nights"],
  },
  {
    id: "event-clinic",
    slug: "serve-receive-lab",
    title: "Serve + Receive Lab",
    kind: "clinic",
    organizationName: "Coach Sam Rivera",
    venueName: "Manhattan Beach Pier",
    startsAt: "2026-08-01T16:00:00.000Z",
    endsAt: "2026-08-01T17:30:00.000Z",
    timezone: "America/Los_Angeles",
    price: { amountMinor: 4800, currency: "USD" },
    spotsRemaining: 3,
    capacity: 8,
    ratingRange: [3.5, 5],
    tags: ["Small group", "Video review"],
  },
  {
    id: "event-open-play",
    slug: "friday-lights-open-play",
    title: "Friday Lights Open Play",
    kind: "open-play",
    organizationName: "Duna House",
    venueName: "Duna House",
    startsAt: "2026-08-01T03:00:00.000Z",
    endsAt: "2026-08-01T06:00:00.000Z",
    timezone: "America/Los_Angeles",
    price: { amountMinor: 1800, currency: "USD" },
    spotsRemaining: 14,
    capacity: 48,
    ratingRange: [2.5, 5.5],
    tags: ["Indoor", "King/Queen", "DJ"],
  },
  {
    id: "event-pickup",
    slug: "golden-hour-fours",
    title: "Golden Hour 4s",
    kind: "pickup",
    organizationName: "Hosted by Theo Park",
    venueName: "Hermosa Beach — Pier Courts",
    startsAt: "2026-07-31T01:00:00.000Z",
    endsAt: "2026-07-31T02:30:00.000Z",
    timezone: "America/Los_Angeles",
    price: { amountMinor: 0, currency: "USD" },
    spotsRemaining: 2,
    capacity: 8,
    ratingRange: [4, 5],
    tags: ["Free", "4s", "Sunset"],
  },
];

export const demoBookings: readonly BookingSummary[] = [
  {
    id: "booking-clinic",
    title: "Serve + Receive Lab",
    kind: "clinic",
    startsAt: "2026-08-01T16:00:00.000Z",
    endsAt: "2026-08-01T17:30:00.000Z",
    venueName: "Manhattan Beach Pier · Court 4",
    status: "confirmed",
    amount: { amountMinor: 4800, currency: "USD" },
    participantNames: ["Mara Lewis"],
  },
  {
    id: "booking-league",
    title: "South Bay Summer Series — Week 5",
    kind: "league",
    startsAt: "2026-08-04T01:00:00.000Z",
    endsAt: "2026-08-04T04:00:00.000Z",
    venueName: "Hermosa Beach — Pier Courts",
    status: "confirmed",
    amount: { amountMinor: 0, currency: "USD" },
    participantNames: [
      "Mara Lewis",
      "Theo Park",
      "Elena Torres",
      "Noa Williams",
    ],
  },
  {
    id: "booking-pickup",
    title: "Golden Hour 4s",
    kind: "pickup",
    startsAt: "2026-07-31T01:00:00.000Z",
    endsAt: "2026-07-31T02:30:00.000Z",
    venueName: "Hermosa Beach — Pier Courts",
    status: "confirmed",
    amount: { amountMinor: 0, currency: "USD" },
    participantNames: ["Mara Lewis", "Theo Park"],
  },
];

export const demoMatches: readonly MatchSummary[] = [
  {
    id: "match-1",
    playedAt: "2026-07-29T01:30:00.000Z",
    venueName: "Manhattan Beach Pier",
    teamA: [demoPeople[0]!, demoPeople[1]!],
    teamB: [demoPeople[2]!, demoPeople[4]!],
    score: [
      [21, 17],
      [18, 21],
      [15, 12],
    ],
    winner: "A",
    ratingDelta: 0.08,
    verification: "live-scored",
  },
  {
    id: "match-2",
    playedAt: "2026-07-26T17:00:00.000Z",
    venueName: "Hermosa Beach — Pier Courts",
    teamA: [demoPeople[0]!, demoPeople[4]!],
    teamB: [demoPeople[1]!, demoPeople[2]!],
    score: [
      [19, 21],
      [16, 21],
    ],
    winner: "B",
    ratingDelta: -0.04,
    verification: "both-confirmed",
  },
  {
    id: "match-3",
    playedAt: "2026-07-22T00:15:00.000Z",
    venueName: "Manhattan Beach Pier",
    teamA: [demoPeople[0]!, demoPeople[3]!],
    teamB: [demoPeople[1]!, demoPeople[4]!],
    score: [
      [21, 13],
      [21, 16],
    ],
    winner: "A",
    ratingDelta: 0.05,
    verification: "group-confirmed",
  },
];

export const demoWalletEntries: readonly WalletEntry[] = [
  {
    id: "wallet-prize",
    kind: "prize",
    description: "Summer Open · 1st place",
    amount: { amountMinor: 18_400, currency: "USD" },
    occurredAt: "2026-07-27T23:42:00.000Z",
    status: "available",
    taxCharacter: "prize",
  },
  {
    id: "wallet-booking",
    kind: "booking",
    description: "Serve + Receive Lab",
    amount: { amountMinor: -4_800, currency: "USD" },
    occurredAt: "2026-07-28T19:14:00.000Z",
    status: "complete",
    taxCharacter: "none",
  },
  {
    id: "wallet-refund",
    kind: "refund",
    description: "Weather credit · Tuesday League",
    amount: { amountMinor: 2_400, currency: "USD" },
    occurredAt: "2026-07-23T03:10:00.000Z",
    status: "available",
    taxCharacter: "none",
  },
];

export const playerMetrics: readonly Metric[] = [
  { label: "Sand Rating", value: "4.62", change: "+0.08", trend: "up" },
  { label: "South Bay rank", value: "#42", change: "Top 9%", trend: "up" },
  { label: "Verified matches", value: "84", change: "7 this month" },
  { label: "Wallet", value: "$184.00", change: "Available" },
];

export const operatorMetrics: readonly Metric[] = [
  { label: "Today’s revenue", value: "$8,420", change: "+18%", trend: "up" },
  { label: "Check-ins", value: "146 / 168", change: "87%" },
  { label: "Court utilization", value: "82%", change: "+6%", trend: "up" },
  { label: "Pending payouts", value: "$2,740", change: "6 recipients" },
];

export const adminMetrics: readonly Metric[] = [
  { label: "Platform GMV", value: "$1.28M", change: "+14.2%", trend: "up" },
  { label: "Active operators", value: "147", change: "+9 this month" },
  { label: "Rated players", value: "24,892", change: "+1,304", trend: "up" },
  {
    label: "Open safety SLAs",
    value: "3",
    change: "1 urgent",
    tone: "warning",
  },
];

export const demoAuditEvents: readonly AuditEvent[] = [
  {
    id: "audit-1",
    occurredAt: "2026-07-30T16:42:00.000Z",
    actorName: "Duna Reconciliation",
    action: "payout.reconciled",
    entity: "Payment payout po_demo_42",
    reason: "Internal ledger and processor report matched exactly.",
    severity: "info",
  },
  {
    id: "audit-2",
    occurredAt: "2026-07-30T16:18:00.000Z",
    actorName: "Avery Chen",
    action: "wallet.payout_held",
    entity: "Wallet · player 9K2",
    reason: "Load-spend-withdraw velocity exceeded the review threshold.",
    severity: "attention",
  },
  {
    id: "audit-3",
    occurredAt: "2026-07-30T15:51:00.000Z",
    actorName: "Sam Rivera",
    action: "eligibility.overridden",
    entity: "Sunset Open · AA division",
    reason: "Imported result was under active identity-resolution review.",
    severity: "attention",
  },
  {
    id: "audit-4",
    occurredAt: "2026-07-30T14:06:00.000Z",
    actorName: "Duna Rating Replay",
    action: "rating.replay_verified",
    entity: "Beach 2s ladder",
    reason: "24,892 player states reproduced bit-for-bit.",
    severity: "info",
  },
];

export const demoFeed = [
  {
    id: "feed-1",
    eyebrow: "RATING MOMENT",
    title: "Mara + Theo closed it in three",
    body: "A 15–12 finish against a higher-rated pair moved Mara to 4.62.",
    meta: "18 minutes ago · Manhattan Beach",
    accent: "aqua",
  },
  {
    id: "feed-2",
    eyebrow: "PURSE PAID",
    title: "$1,500 landed before sunset",
    body: "The Summer Open purse reached eight player wallets within 92 seconds of bracket close.",
    meta: "Sunday · Hermosa Beach",
    accent: "flare",
  },
  {
    id: "feed-3",
    eyebrow: "NEARBY",
    title: "Two spots at Golden Hour 4s",
    body: "Theo is hosting a 4.0–5.0 run tonight. Your regular partner is already in.",
    meta: "Tonight, 6:00 PM · 1.8 mi",
    accent: "sand",
  },
] as const;

export const demoOperatorSchedule = [
  {
    time: "7:00",
    court: "1–4",
    title: "Junior Elite — Morning Block",
    detail: "32 athletes · Coaches Sam, Mia, Jules",
    state: "live",
  },
  {
    time: "9:30",
    court: "1–2",
    title: "Serve + Receive Lab",
    detail: "8 / 8 · Waitlist 3",
    state: "full",
  },
  {
    time: "11:00",
    court: "3",
    title: "Private · Mara / Coach Theo",
    detail: "$95 · Paid",
    state: "paid",
  },
  {
    time: "1:00",
    court: "1–6",
    title: "Sunset Open — Qualifier",
    detail: "32 teams · $1,500 purse",
    state: "attention",
  },
  {
    time: "6:00",
    court: "1–4",
    title: "Tuesday Co-ed 4s",
    detail: "Week 5 · Work teams assigned",
    state: "scheduled",
  },
] as const;

export const demoAdminQueues = [
  {
    id: "queue-minor",
    title: "Minor-safety report",
    detail: "Coach-to-player thread · guardian copy present",
    age: "11 min",
    sla: "49 min remaining",
    priority: "urgent",
  },
  {
    id: "queue-wallet",
    title: "Wallet velocity review",
    detail: "Three card loads → same-day instant withdrawal attempt",
    age: "24 min",
    sla: "3h 36m remaining",
    priority: "high",
  },
  {
    id: "queue-rating",
    title: "Rating integrity signal",
    detail: "Dense opponent graph · 12 low-variance results",
    age: "1h",
    sla: "23h remaining",
    priority: "normal",
  },
] as const;

export function demoWalletBalanceMinor(): number {
  return demoWalletEntries.reduce(
    (sum, entry) => sum + entry.amount.amountMinor,
    0,
  );
}
