ALTER TABLE "organization_invitations" DROP CONSTRAINT "organization_invitation_destination_present";--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD COLUMN "event_session_id" uuid;--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD COLUMN "event_division_id" uuid;--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD COLUMN "provisional_person_id" uuid;--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD COLUMN "event_registration_id" uuid;--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD COLUMN "team_entry_id" uuid;--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD COLUMN "event_payment_treatment" varchar(24);--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD CONSTRAINT "organization_invitations_event_session_id_sessions_id_fk" FOREIGN KEY ("event_session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD CONSTRAINT "organization_invitations_event_division_id_divisions_id_fk" FOREIGN KEY ("event_division_id") REFERENCES "public"."divisions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD CONSTRAINT "organization_invitations_provisional_person_id_people_id_fk" FOREIGN KEY ("provisional_person_id") REFERENCES "public"."people"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD CONSTRAINT "organization_invitations_event_registration_id_registrations_id_fk" FOREIGN KEY ("event_registration_id") REFERENCES "public"."registrations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD CONSTRAINT "organization_invitations_team_entry_id_team_entries_id_fk" FOREIGN KEY ("team_entry_id") REFERENCES "public"."team_entries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "organization_invitation_event_registration_idx" ON "organization_invitations" USING btree ("event_registration_id");--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD CONSTRAINT "organization_invitation_event_payment_valid" CHECK ("organization_invitations"."event_payment_treatment" IS NULL OR "organization_invitations"."event_payment_treatment" IN ('complimentary', 'to-be-paid'));--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD CONSTRAINT "organization_invitation_event_context_complete" CHECK (("organization_invitations"."event_session_id" IS NULL AND "organization_invitations"."event_division_id" IS NULL AND "organization_invitations"."provisional_person_id" IS NULL AND "organization_invitations"."event_registration_id" IS NULL AND "organization_invitations"."team_entry_id" IS NULL AND "organization_invitations"."event_payment_treatment" IS NULL) OR ("organization_invitations"."event_session_id" IS NOT NULL AND "organization_invitations"."event_division_id" IS NOT NULL AND "organization_invitations"."provisional_person_id" IS NOT NULL AND "organization_invitations"."event_registration_id" IS NOT NULL AND "organization_invitations"."team_entry_id" IS NOT NULL AND "organization_invitations"."event_payment_treatment" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "organization_invitations" ADD CONSTRAINT "organization_invitation_destination_present" CHECK ("organization_invitations"."invited_email" IS NOT NULL OR "organization_invitations"."invited_phone_e164" IS NOT NULL OR "organization_invitations"."guardian_email" IS NOT NULL OR "organization_invitations"."guardian_phone_e164" IS NOT NULL OR "organization_invitations"."event_registration_id" IS NOT NULL);