import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, join, relative, resolve } from "node:path";
import { format } from "prettier";

async function main() {
  const root = resolve(import.meta.dirname, "..");
  const outputPath = join(
    root,
    "packages/api/src/generated/duna-feature-knowledge.ts",
  );
  const surfaceDirectory = join(root, "docs/surfaces");
  const sourcePaths = [
    join(root, "docs/BUILD_MATRIX.md"),
    join(root, "packages/api/src/router.ts"),
    ...readdirSync(surfaceDirectory)
      .filter((name) => name.endsWith(".md") && name !== "README.md")
      .sort()
      .map((name) => join(surfaceDirectory, name)),
  ];

  const sourceFingerprint = createHash("sha256")
    .update(
      sourcePaths
        .map(
          (path) =>
            `${relative(root, path)}\n${readFileSync(path, "utf8").replaceAll("\r\n", "\n")}`,
        )
        .join("\n---\n"),
    )
    .digest("hex");

  const buildMatrix = readFileSync(join(root, "docs/BUILD_MATRIX.md"), "utf8");
  const modules = buildMatrix
    .split("\n")
    .filter((line) => /^\| M\d+\s/.test(line))
    .map((line) =>
      line
        .split("|")
        .slice(1, -1)
        .map((cell) => cell.trim()),
    )
    .filter((cells) => cells.length >= 4)
    .map(([module = "", surfaces = "", _evidence = "", status = ""]) => {
      const match = module.match(/^(M\d+)\s+(.+)$/);
      return {
        id: match?.[1] ?? module,
        name: match?.[2] ?? module,
        surfaces: surfaces
          .split(",")
          .map((surface) => surface.trim())
          .filter(Boolean),
        status: status.replaceAll(/\[([^\]]+)\]\([^\)]+\)/g, "$1"),
      };
    });

  const routerSource = readFileSync(
    join(root, "packages/api/src/router.ts"),
    "utf8",
  );
  const apiCapabilities = [
    ...routerSource.matchAll(
      /^\s{2}([A-Za-z][A-Za-z0-9]*):\s+(?:publicProcedure|protectedProcedure|organizationProcedure|adminProcedure|superAdminProcedure)/gm,
    ),
  ]
    .map((match) => match[1]!)
    .filter((name, index, all) => all.indexOf(name) === index)
    .sort();

  const surfaceGuides = sourcePaths
    .filter((path) => path.startsWith(surfaceDirectory))
    .map((path) => {
      const markdown = readFileSync(path, "utf8");
      const paragraphs = markdown
        .split(/\n\s*\n/)
        .map((paragraph) => paragraph.replaceAll(/\s+/g, " ").trim())
        .filter(
          (paragraph) =>
            paragraph &&
            !paragraph.startsWith("#") &&
            !paragraph.startsWith("|") &&
            !paragraph.startsWith("```") &&
            !paragraph.startsWith("-"),
        );
      return {
        surface: basename(path, ".md"),
        summary: paragraphs[0] ?? "",
        capabilities: [...markdown.matchAll(/^##\s+(.+)$/gm)].map((match) =>
          match[1]!.trim(),
        ),
      };
    });

  const rendered = await format(
    `// This file is generated by scripts/generate-duna-feature-knowledge.ts.\n// Update Duna surface docs, BUILD_MATRIX, or API procedures, then run pnpm knowledge:generate.\n\nexport const generatedDunaFeatureKnowledge = ${JSON.stringify(
      { sourceFingerprint, modules, apiCapabilities, surfaceGuides },
      null,
      2,
    )} as const;\n`,
    { parser: "typescript" },
  );

  if (process.argv.includes("--check")) {
    const current = readFileSync(outputPath, "utf8");
    if (current !== rendered) {
      console.error(
        "Duna AI feature knowledge is stale. Run pnpm knowledge:generate and commit the generated manifest.",
      );
      process.exitCode = 1;
    }
  } else {
    writeFileSync(outputPath, rendered);
  }
}

void main();
